-- schema.sql
-- Boostear Database Schema - Venezuela Compliance
-- Generated by Antigravity

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. CONFIGURATION & PROJECTS
-- ==========================================

CREATE TABLE projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    client VARCHAR(255),
    location VARCHAR(255),
    start_date DATE,
    duration_months INTEGER,
    status VARCHAR(20) DEFAULT 'DRAFT', -- DRAFT, ACTIVE, FROZEN, ARCHIVED
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Project Specific Configuration (FCAS, Currency, Laws)
CREATE TABLE projects_config (
    project_id UUID PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,
    
    -- Currency Base
    base_currency_iso VARCHAR(3) DEFAULT 'USD', -- The "Anchor" currency
    exchange_rate_ref DECIMAL(18, 4) NOT NULL DEFAULT 1.0000, -- e.g., 50.00 Bs/USD
    
    -- FCAS Parameters (Venezuelan Labor Law)
    fcas_interest_rate DECIMAL(5, 2) DEFAULT 0.00, -- Tasa Interes Prestaciones
    vacation_days_base INTEGER DEFAULT 15,
    bonus_days_base INTEGER DEFAULT 45, -- Utilidades
    holidays_count INTEGER DEFAULT 12, -- Días Feriados
    avg_sickness_days INTEGER DEFAULT 3, -- Permisos Promedio
    
    -- Contributions (Aportes Patronales)
    ivss_pct DECIMAL(5, 2) DEFAULT 11.00, -- Default 9-11%
    faov_pct DECIMAL(5, 2) DEFAULT 2.00,
    inces_pct DECIMAL(5, 2) DEFAULT 2.00,
    
    -- Ley de Pensiones 2025
    pension_law_pct DECIMAL(5, 2) DEFAULT 9.00,
    pension_apply_to_fcas BOOLEAN DEFAULT TRUE, -- TRUE: Inside FCAS, FALSE: Separate Indirect
    
    -- Indirect Costs
    admin_pct DECIMAL(5, 2) DEFAULT 15.00,
    profit_pct DECIMAL(5, 2) DEFAULT 10.00,
    vat_pct DECIMAL(5, 2) DEFAULT 16.00
);

-- ==========================================
-- 2. MASTER CATALOG (GLOBAL RESOURCES)
-- ==========================================

-- Master Materials
CREATE TABLE insumos_materiales (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    codigo_covenin VARCHAR(50) UNIQUE, -- Indexed unique code
    nombre VARCHAR(255) NOT NULL,
    unidad VARCHAR(20) NOT NULL,
    familia VARCHAR(100), -- e.g. "Aceros", "Agregados"
    
    -- Dual Currency Core
    costo_bs DECIMAL(18, 4) DEFAULT 0,
    costo_usd DECIMAL(18, 4) DEFAULT 0,
    tasa_cambio DECIMAL(10, 4) DEFAULT 1,
    fecha_referencia TIMESTAMP DEFAULT NOW(),
    
    is_active BOOLEAN DEFAULT TRUE
);

-- Master Equipment (Includes COP Logic)
CREATE TABLE insumos_equipos (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    codigo VARCHAR(50) UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    tipo VARCHAR(50), -- Maquinaria, Vehiculo, Equipo Menor
    
    -- COP Calculation Parameters
    valor_adquisicion DECIMAL(18, 4) DEFAULT 0, -- Va
    vida_util_horas INTEGER DEFAULT 10000, -- Ve
    valor_rescate_pct DECIMAL(5, 2) DEFAULT 20.00, -- p% of Va
    factor_mantenimiento DECIMAL(5, 2) DEFAULT 0.80, -- K
    
    -- Operating Consumption
    potencia_hp DECIMAL(10, 2),
    consumo_combustible_hora DECIMAL(10, 4), -- Galones/Litros por hora
    costo_lubricante_factor DECIMAL(5, 2) DEFAULT 0.10, -- % of fuel cost
    
    -- Calculated Daily Rate Cache
    costo_dia_bs DECIMAL(18, 4),
    costo_dia_usd DECIMAL(18, 4),
    tasa_cambio DECIMAL(10, 4),
    fecha_referencia TIMESTAMP DEFAULT NOW()
);

-- Master Labor (Tabulador de Oficios)
CREATE TABLE tabulador_mano_obra (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    codigo VARCHAR(50) UNIQUE,
    cargo VARCHAR(255) NOT NULL, -- Maestro, Ayudante, etc.
    grupo VARCHAR(50), -- Obrero, Empleado
    
    -- Salary Components
    salario_base_diario_bs DECIMAL(18, 4) DEFAULT 0,
    salario_base_diario_usd DECIMAL(18, 4) DEFAULT 0,
    bono_alimentacion_diario_bs DECIMAL(18, 4) DEFAULT 0, -- Cestaticket logic
    bono_alimentacion_diario_usd DECIMAL(18, 4) DEFAULT 0,
    
    tasa_cambio DECIMAL(10, 4),
    fecha_referencia TIMESTAMP DEFAULT NOW()
);

-- ==========================================
-- 3. PROJECT LOCAL RESOURCES (SNAPSHOTS)
-- ==========================================
-- NOTE: These tables isolate project costs from global market fluctuations.

CREATE TABLE project_materials (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    original_materail_id UUID REFERENCES insumos_materiales(id), -- Optional link back
    
    codigo_covenin VARCHAR(50),
    nombre VARCHAR(255) NOT NULL,
    unidad VARCHAR(20),
    
    -- Frozen Costs for this Project
    costo_bs DECIMAL(18, 4) NOT NULL,
    costo_usd DECIMAL(18, 4) NOT NULL,
    tasa_cambio DECIMAL(10, 4) NOT NULL,
    fecha_referencia TIMESTAMP DEFAULT NOW(),
    
    UNIQUE(project_id, codigo_covenin)
);

CREATE TABLE project_labor (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    original_labor_id UUID REFERENCES tabulador_mano_obra(id),
    
    cargo VARCHAR(255),
    
    salario_base_diario_bs DECIMAL(18, 4) NOT NULL,
    salario_base_diario_usd DECIMAL(18, 4) NOT NULL,
    bono_alimentacion_diario_bs DECIMAL(18, 4),
    bono_alimentacion_diario_usd DECIMAL(18, 4),
    tasa_cambio DECIMAL(10, 4) NOT NULL
);

CREATE TABLE project_equipment (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    original_equipment_id UUID REFERENCES insumos_equipos(id),
    
    nombre VARCHAR(255),
    costo_dia_bs DECIMAL(18, 4) NOT NULL,
    costo_dia_usd DECIMAL(18, 4) NOT NULL,
    tasa_cambio DECIMAL(10, 4) NOT NULL
);

-- ==========================================
-- 4. APU STRUCTURE (Analysis of Unit Prices)
-- ==========================================

-- Partidas (Headers)
CREATE TABLE apu_partidas (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    
    codigo VARCHAR(50) NOT NULL, -- e.g. "3.1"
    descripcion TEXT NOT NULL,
    unidad VARCHAR(20) NOT NULL,
    cantidad DECIMAL(18, 4) DEFAULT 0, -- Metrado final
    
    rendimiento DECIMAL(18, 4) NOT NULL DEFAULT 1, -- CRITICAL: Yield per day
    
    -- Calculated Cache (Optional, for fast read)
    precio_unitario_bs DECIMAL(18, 4),
    precio_unitario_usd DECIMAL(18, 4),
    
    last_calculated_at TIMESTAMP
);

-- APU Detalle (Items inside the analysis)
CREATE TABLE apu_detalles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    partida_id UUID REFERENCES apu_partidas(id) ON DELETE CASCADE,
    
    -- Polymorphic relation to Project Resources (Manual implementation)
    resource_type VARCHAR(20) NOT NULL, -- 'MATERIAL', 'LABOR', 'EQUIPMENT'
    resource_id UUID NOT NULL, -- Points to project_materials, project_labor, or project_equipment
    
    cantidad DECIMAL(18, 6) NOT NULL, -- coeff per unit. 6 decimals for precision
    desperdicio_pct DECIMAL(5, 2) DEFAULT 0.00, -- Waste factor (e.g. 5%)
    
    -- Calculated subtotal cache
    costo_total_renglon_bs DECIMAL(18, 4),
    costo_total_renglon_usd DECIMAL(18, 4)
);

-- Index recommendations
CREATE INDEX idx_projects_status ON projects(status);
CREATE INDEX idx_apu_partidas_project ON apu_partidas(project_id);
CREATE INDEX idx_apu_detalles_partida ON apu_detalles(partida_id);
