-- schema.sql
-- Boostear Database Schema - Venezuela Compliance
-- Generated by Antigravity

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. CONFIGURATION & PROJECTS
-- ==========================================

CREATE TABLE projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    client VARCHAR(255),
    location VARCHAR(255),
    start_date DATE,
    duration_months INTEGER,
    status VARCHAR(20) DEFAULT 'DRAFT', -- DRAFT, ACTIVE, FROZEN, ARCHIVED
    
    -- New: Full persistence of frontend config state
    config JSONB DEFAULT '{}'::jsonb,
    
    -- Cache for Project Totals (Dual Currency)
    costo_total_bs DECIMAL(18, 4) DEFAULT 0,
    costo_total_usd DECIMAL(18, 4) DEFAULT 0,
    
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Project Specific Configuration (Relational Backup for Analytics)
-- This mirrors the 'config' JSONB but in relational columns for SQL querying
CREATE TABLE projects_config (
    project_id UUID PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,
    
    -- Currency Base
    base_currency_iso VARCHAR(3) DEFAULT 'USD',
    exchange_rate DECIMAL(18, 4) NOT NULL DEFAULT 1.0000,
    exchange_rate_date TIMESTAMP,
    exchange_rate_source VARCHAR(50) DEFAULT 'MANUAL',
    
    -- FCAS Parameters
    vacation_days_base INTEGER DEFAULT 15,
    bonus_days_base INTEGER DEFAULT 45,
    holidays_count INTEGER DEFAULT 12,
    avg_sickness_days INTEGER DEFAULT 3,
    
    -- Contributions
    ivss_pct DECIMAL(5, 2) DEFAULT 11.00,
    faov_pct DECIMAL(5, 2) DEFAULT 2.00,
    inces_pct DECIMAL(5, 2) DEFAULT 2.00,
    
    -- Pension Law 2025
    pension_law_pct DECIMAL(5, 2) DEFAULT 9.00,
    pension_apply_to_fcas BOOLEAN DEFAULT TRUE,
    
    -- Indirect Costs
    admin_pct DECIMAL(5, 2) DEFAULT 15.00,
    profit_pct DECIMAL(5, 2) DEFAULT 10.00,
    vat_pct DECIMAL(5, 2) DEFAULT 16.00,
    
    -- Calculated Factors Cache
    fcas_factor_total DECIMAL(10, 4) DEFAULT 0
);

-- ==========================================
-- 2. MASTER CATALOG (GLOBAL RESOURCES)
-- ==========================================

-- Master Materials
CREATE TABLE insumos_materiales (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    codigo_covenin VARCHAR(50) UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    unidad VARCHAR(20) NOT NULL,
    familia VARCHAR(100),
    
    -- Dual Currency Core
    costo_bs DECIMAL(18, 4) DEFAULT 0,
    costo_usd DECIMAL(18, 4) DEFAULT 0,
    tasa_cambio DECIMAL(10, 4) DEFAULT 1,
    fecha_referencia TIMESTAMP DEFAULT NOW(),
    
    is_active BOOLEAN DEFAULT TRUE
);

-- Master Equipment
CREATE TABLE insumos_equipos (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    codigo VARCHAR(50) UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    tipo VARCHAR(50), 
    
    -- COP Parameters
    valor_adquisicion DECIMAL(18, 4) DEFAULT 0,
    vida_util_horas INTEGER DEFAULT 10000,
    valor_rescate_pct DECIMAL(5, 2) DEFAULT 20.00,
    factor_mantenimiento DECIMAL(5, 2) DEFAULT 0.80,
    
    -- Calculated Daily Rate Cache
    costo_dia_bs DECIMAL(18, 4),
    costo_dia_usd DECIMAL(18, 4),
    tasa_cambio DECIMAL(10, 4),
    fecha_referencia TIMESTAMP DEFAULT NOW()
);

-- Master Labor
CREATE TABLE tabulador_mano_obra (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    codigo VARCHAR(50) UNIQUE,
    cargo VARCHAR(255) NOT NULL,
    grupo VARCHAR(50),
    
    -- Salary Components
    salario_base_diario_bs DECIMAL(18, 4) DEFAULT 0,
    salario_base_diario_usd DECIMAL(18, 4) DEFAULT 0,
    bono_alimentacion_diario_bs DECIMAL(18, 4) DEFAULT 0,
    bono_alimentacion_diario_usd DECIMAL(18, 4) DEFAULT 0,
    
    tasa_cambio DECIMAL(10, 4),
    fecha_referencia TIMESTAMP DEFAULT NOW()
);

-- ==========================================
-- 3. APU STRUCTURE (Analysis of Unit Prices)
-- ==========================================

-- Partidas (Headers)
CREATE TABLE apu_partidas (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    
    codigo VARCHAR(50) NOT NULL,
    descripcion TEXT NOT NULL,
    unidad VARCHAR(20) NOT NULL,
    cantidad DECIMAL(18, 4) DEFAULT 0,
    rendimiento DECIMAL(18, 4) NOT NULL DEFAULT 1,
    
    capitulo VARCHAR(100),
    
    -- Cost Cache (Dual Currency)
    costo_materiales_bs DECIMAL(18, 4) DEFAULT 0,
    costo_materiales_usd DECIMAL(18, 4) DEFAULT 0,
    
    costo_mano_obra_bs DECIMAL(18, 4) DEFAULT 0,
    costo_mano_obra_usd DECIMAL(18, 4) DEFAULT 0,
    
    costo_equipos_bs DECIMAL(18, 4) DEFAULT 0,
    costo_equipos_usd DECIMAL(18, 4) DEFAULT 0,
    
    costo_directo_bs DECIMAL(18, 4) DEFAULT 0,
    costo_directo_usd DECIMAL(18, 4) DEFAULT 0,
    
    precio_unitario_bs DECIMAL(18, 4) DEFAULT 0,
    precio_unitario_usd DECIMAL(18, 4) DEFAULT 0,
    
    precio_total_bs DECIMAL(18, 4) DEFAULT 0,
    precio_total_usd DECIMAL(18, 4) DEFAULT 0,
    
    last_calculated_at TIMESTAMP
);

-- APU Detalle
CREATE TABLE apu_detalles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    partida_id UUID REFERENCES apu_partidas(id) ON DELETE CASCADE,
    
    resource_type VARCHAR(20) NOT NULL, -- 'MATERIAL', 'LABOR', 'EQUIPMENT'
    resource_name VARCHAR(255), -- Denormalized name for display
    
    cantidad DECIMAL(18, 6) NOT NULL,
    desperdicio_pct DECIMAL(5, 2) DEFAULT 0.00,
    
    -- Unit Prices Snapshot (Dual)
    precio_unitario_bs DECIMAL(18, 4) DEFAULT 0,
    precio_unitario_usd DECIMAL(18, 4) DEFAULT 0,
    
    -- Subtotals (Dual)
    subtotal_bs DECIMAL(18, 4) DEFAULT 0,
    subtotal_usd DECIMAL(18, 4) DEFAULT 0
);

-- Indices
CREATE INDEX idx_projects_status ON projects(status);
CREATE INDEX idx_apu_partidas_project ON apu_partidas(project_id);
CREATE INDEX idx_apu_detalles_partida ON apu_detalles(partida_id);
